config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'

  get 'users/new'  
  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  resources :messages
  get 'contact' => 'messages#new'
  get 'news' => 'static_pages#news'
  get 'signup' => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  delete 'destroy' => 'carts#destroy'
  resources :users
  resources :categories, param: :categoryid
  resources :products, param: :productid do
    get :autocomplete_product_productname, :on => :collection
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resource :cart, only: [ :show ] do
    post "add", path: "add/:productid"
	get :checkout
  end
  get 'orders/order_history' => 'orders#order_history'
  resources :orders, only: [:index, :show, :create, :update] do
    member do
	  get :new_payment
	  post :pay
    end
  end
  
  get '*path' => redirect('/')

end

app/models/cart.rb
class Cart 
attr_reader :products

QUANTITIES=[
    ["1", 1],
	["2", 2],
	["3", 3],
	["4", 4],
	["5", 5],
	["6", 6],
	["7", 7],
	["8", 8],
	["9", 9],
	["10", 10]
  ]

  def self.build_from_hash hash
    products= if hash["cart"] then
	  hash["cart"]["products"].map do |product|
	    CartItem.new product["productid"], product["quantity"]
	  end
	else
	  []
	end
	new products
  end
  
  def initialize products=[]
    @products= products
  end
  
  def add_product productid
    product = @products.find{ |product| product.productid == productid }
	if product
	  product.quantity_increment
	else
      @products << CartItem.new(productid)
    end
  end
  
  
  def is_empty?
    @products.empty?
  end
  
  def product_count
    @products.length
  end
  
  def serialize
    products = @products.map do |product| 
	{"productid" => product.productid, "quantity" => product.quantity}
	end
    {
	  "products" => products
	}
  end
  
  def total_cost
    @products.inject(0) { |sum, product| sum + product.total_cost }
  end
  
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_filter :get_cart
  before_action :sign_in_user, only: [:checkout]
  
  def add
    @cart.add_product params[:productid]
	session["cart"] = @cart.serialize
	product= Product.find(params[:productid])
    flash[:success] = "Added #{product.productname} to cart"
    redirect_to :back
  end
  
   def destroy
    session["cart"]= Hash.new(0)
	session["cart"] = @cart.serialize
	session["cart"]["products"].delete_if {|hash| hash["productid"] == params[:productid]  } 
	product= Product.find(params[:productid])
    flash[:success] = "Removed #{product.productname} from cart"
    redirect_to cart_path	
  end
  
  def show
  end
  
  def update
    product.unitcost.to_s.gsub(/[$,]/,'').to_f * quantity
	redirect_to carts_path
  end
  
  def checkout
    @order_form= OrderForm.new user: User.new
	@client_token = Braintree::ClientToken.generate
  end
  
  private 
  
  def sign_in_user
    unless logged_in?
	  store_location
      flash[:danger] = "Please Sign in."
      redirect_to login_url
    end
  end
end

app/views/carts/checkout.html.erb
<html>
<h3> Checkout </h3>
<hr/>
<ul>
  <% @cart.products.each do |product| %>
    <li>
      <span>
	    <%= product.quantity %>
        <%= product.product.productname %>
         <%= number_to_currency product.total_cost %>
	  </span>
	</li>
  <% end %>
</ul>

<p>
  <strong>
    Total price:
    <%= number_to_currency @cart.total_cost %>
  </strong>
</p>

<%= form_for @order_form, url: orders_path do |form| %>
  <%= render 'orders/error_messages' %>
  <%= form.fields_for :address, form.object.address do |address| %>
    <div class= "form-group">
      <p> <%= address.text_field :fullname, placeholder: "Enter Name", class: "form-control" %> </p>
      <p> <%= address.text_field :address_line_1, placeholder: "Address Line 1", class: "form-control" %> </p>
	  <p> <%= address.text_field :address_line_2, placeholder: "Address Line 2", class: "form-control" %> </p>
      <p> <%= address.text_field :city, placeholder: "City", class: "form-control" %> </p>
	  <p> <%= address.text_field :region, placeholder: "State / Region", class: "form-control" %> </p>
	  <p> <%= address.text_field :postal_code, placeholder: "Postal code / Zipcode", class: "form-control" %> </p>
      <p> <%= address.country_select :country, { priority_countries: [ "GB", "US", "DE", "IN", "CN", "JP", "PT","ES"] }, { class: "form-control" } %> </p>
	  <p> <%= address.text_field :phone, class: "form-control", placeholder: "Phone" %> </p>
    </div>
	
	<div id="dropin"></div>
    <p> <%= form.submit "Place order", class: "btn btn-primary" %>
  <% end %>
<% end %>

<script>

// We generated a client token for you so you can test out this code
// immediately. In a production-ready integration, you will need to
// generate a client token on your server (see section below).
var clienttoken= '<%= @client_token %> ';
braintree.setup(clienttoken, 'dropin', {
    container: 'dropin'
  });
  
</script>
</html>

app/views/carts/show.html.erb
<h3> Shopping cart </h3>
<hr/>

<div>
  <% @cart.products.each do |product| %>
    <div class="row">
      <div class="col-sm-2">
          <%= image_tag product.product.remoteproductimage %>
		  <%= link_to 'Remove',  {:controller => "carts", :action => "destroy", :productid => product.productid },:method => :delete, :data => { :confirm => 'Are you sure you want to delete this product from the cart?'+product.productid }%>
      </div>
      <div class="col-sm-6">
	    <%= link_to product.product.productname, product.product %> 
	  </div>
	  <div class="col-sm-2">
	     <%= number_to_currency product.total_cost %> 
	  </div>
      <div class="col-sm-2">
   	    <%= product.quantity %>
	  </div>
	</div> <br/>
  <% end %> 
<div>
    <div class="row">
      <div class="col-sm-4">
        <strong>
          Total: 
          <%= number_to_currency @cart.total_cost %>
		</strong>
	  </div>
	</div>
  </div>
</div>

<% if session["cart"]%>
  <p> <%=link_to "Proceed to checkout", checkout_cart_path, class: "btn btn-primary" %> </p>
<% end %>

<script>
  $(function() {
    $("form select").on("change", function() {
      $(this).parent("form").submit();
    });
  });