config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'

  get 'users/new'  
  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  resources :messages
  get 'contact' => 'messages#new'
  get 'news' => 'static_pages#news'
  get 'signup' => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  delete 'destroy' => 'carts#destroy'
  resources :users
  resources :categories, param: :categoryid
  resources :products, param: :productid do
    get :autocomplete_product_productname, :on => :collection
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resource :cart, only: [ :show ] do
    post "add", path: "add/:productid"
	get :checkout
  end
  get 'orders/order_history' => 'orders#order_history'
  resources :orders, only: [:index, :show, :create, :update] do
    member do
	  get :new_payment
	  post :pay
    end
  end
  
  get '*path' => redirect('/')

end

app/models/category.rb
class Category < ActiveRecord::Base
  self.table_name="categories"
  self.primary_key="categoryid"
  has_many :products, dependent: :destroy
  
    SORT_VALUES=[
    [ "Price: High to Low", :desc],
	["Price: Low to High", :asc]
  ]
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
before_action :set_category, only: [:show, :edit, :update, :destroy]
before_action :admin_user, only: [ :new, :edit, :update, :create, :destroy, :index ]
  def new
    @category= Category.new
  end
  
  def edit
  end
  
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
	    flash[:success] = 'Category was successfully created.'
        format.html { redirect_to categories_url }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update
    respond_to do |format|
      if @category.update(category_params)
	    flash[:success]= 'Category is updated' 
        format.html { redirect_to categories_url }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def index
    @categories = Category.all # getting all the users!
  end
  
  def show
    if params[:sort_value]
      @products = @category.products.search(params[:search]).order('unitcost '+params[:sort_value]).paginate(page: params[:page], per_page: 24)
    else
	  @products = @category.products.search(params[:search]).paginate(page: params[:page], per_page: 24)
	end
  end
  
  def destroy
    @category.destroy
    respond_to do |format|
	  flash[:success] = 'Category was successfully destroyed.' 
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
  
  private
    def set_category
	  begin
        @category = Category.includes(:products).find(params[:categoryid])
	  rescue ActiveRecord::RecordNotFound
	    flash[:warning] = "Category Not Found"
	    redirect_to root_path 
	  end
    end
	
    def category_params
      params.require(:category).permit(:categoryname)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-1">
<%= form_for @category do |f| %>
  <% if @category.errors.any? %>
    <h2> <%= "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:" %>
    <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li> <%= msg %> </li>
	  <% end %>
	</ul>
  <% end %>
   
  <%= f.label :name %>
  <%= f.text_field :categoryname %>
  
  <div class="row">
	<div class="col-sm-4">
      <%= f.submit 'Save', class: "btn btn-primary buttonColor" %>
    </div>
    <div class="col-md-4">		
      <%= link_to 'Show', @category %>
    </div>
    <div class="col-md-4">
      <%= link_to 'Back', categories_path %>
    </div>
  </div>
<% end %>
  </div>
</div>

app/views/categories/edit.html.erb
<h1> Edit Category </h1>

<%= render 'category' %>

app/views/categories/index.html.erb
<h3>All categories</h3>
<hr/>


<% @categories.each do |category| %>
  <div class="row">
    <div class="col-sm-2">
	  <span class="category"><%= category.categoryname %></span>
    </div>

	<% if current_user && current_user.admin? %>
	  <div class="col-sm-2">
	    <%= link_to 'Show', category %>
	  </div>
	  <div class="col-sm-2">
        <%= link_to 'Edit', edit_category_path(category) %>
	  </div>
	  <div class="col-sm-2">
        <%= link_to 'Destroy', category, :method => :delete, :data => { :confirm => 'Are you sure you want to delete this category?' } %>
	  </div>
    <% end %> 
	<div class="col-sm-4"> </div> 
  </div>
<% end %>
<hr/>
<% if current_user && current_user.admin? %>
  <%= link_to 'New Category', new_category_path, :class => "btn btn-primary buttonColor" %>
<% end %>

app/views/categories/new.html.erb
<h1> New category </h1>

<%= render 'category' %>

app/views/categories/show.html.erb
<%= form_tag category_path, :method => 'get', :id => "product_sort" do %>
  
  <div class="row">
    <div class="col-sm-4">
	  <h3> <%= @category.categoryname %>  (<%= @products.count %>)</h3>
	</div>
    <div class="col-sm-4"></div>
    <div class="col-sm-4">
      <%= select_tag "sort_value", options_for_select(Category::SORT_VALUES), {:class => 'form-control',:prompt => "Sort"}%>
	</div>
  </div>
  
<% end %>
  <%=render "products/productCategory", products: @products %>

<script>
  $(function() {
    $("form select").on("change", function() {
      $(this).closest("form").submit();
    });
  });
</script>