config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'

  get 'users/new'  
  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  resources :messages
  get 'contact' => 'messages#new'
  get 'news' => 'static_pages#news'
  get 'signup' => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  delete 'destroy' => 'carts#destroy'
  resources :users
  resources :categories, param: :categoryid
  resources :products, param: :productid do
    get :autocomplete_product_productname, :on => :collection
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resource :cart, only: [ :show ] do
    post "add", path: "add/:productid"
	get :checkout
  end
  get 'orders/order_history' => 'orders#order_history'
  resources :orders, only: [:index, :show, :create, :update] do
    member do
	  get :new_payment
	  post :pay
    end
  end
  
  get '*path' => redirect('/')

end

app/models/product.rb
class Product < ActiveRecord::Base
  self.table_name="products"
  self.primary_key="productid"
  
  mount_uploader :productimage, ProductimageUploader
  belongs_to :category
  has_many :order_items
  validates_presence_of :productname,:unitcost
  
  SORT_VALUES=[
    [ "Price: High to Low", :desc],
	["Price: Low to High", :asc]
  ]
  
  
    
  def image_url
    productimage.present? ? productimage_url : remoteproductimage	
  end
  
  def self.search(search)
    if search
      where('lower(productname) LIKE ?', "%#{search.downcase}%")
    else
      all
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_filter :get_cart
  before_action :admin_user, only: [ :new, :edit, :update, :create, :destroy ]
  autocomplete :product, :productname
  
  
  def new
  	@product= Product.new
  end
  
  def index
    if params[:sort_value]
  	  @products= Product.search(params[:search]).order('unitcost ' + params[:sort_value]).paginate(page: params[:page], per_page: 24)
    else
	  @products= Product.search(params[:search]).paginate(page: params[:page], per_page: 24)
	end  
  end
  
  def show
  end
  
  def edit
  end
  
  def create
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
	    flash[:success] = "Product was successfully created."
        format.html { redirect_to @product}
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end
  
   def update
    respond_to do |format|
      if @product.update(product_params)
	    flash[:success] = "You have successfully updated the product."
        format.html { redirect_to @product}
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @product.destroy
    respond_to do |format|
	  flash[:success] = 'Product is deleted' 
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
  
   private
    def set_product
      @product = Product.find(params[:productid])
    end
	

	def product_params
      params.require(:product).permit(:productname, :unitcost, :productimage,:remoteproductimage, :category_id)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_product.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-1">
    <%= form_for(@product, :html => { :multipart => true }) do |f| %>
      <% if @product.errors.any? %>
        #error_explanation
        <h2> <%= "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:" %> </h2>
        <ul>
          <%= @product.errors.full_messages.each do |msg| %>
            <li> <%= msg %></li>
		  <% end %>
	    </ul>
      <% end %>
  
      <%= f.label :name %>
      <%= f.text_field :productname %>
   
      <%= f.label :price %>
      <%= f.text_field :unitcost %>
      
      <%= f.label :image %>
      <%= f.file_field :productimage %>
      
      <%= f.label :category %>
      <%= f.select :category_id, Category.all.map { |c| [ c.categoryname, c.categoryid ] } %>
      
	  <div class="row">
	    <div class="col-sm-4">
          <%= f.submit 'Save', class: "btn btn-primary buttonColor" %>
		</div>
		<div class="col-md-4">		
	      <%= link_to 'Show', @product %>
		</div>
		<div class="col-md-4">
          <%= link_to 'All Products', products_path %>
		</div>
	  </div>
<% end %>
  </div>
</div>

app/views/products/_productCategory.html.erb
<% if @products.any? %>
   
  <div class="row">
    <div class="col-sm-2"></div>
    <div class="col-sm-8">
      <%= will_paginate  @products %>
    </div>
    <div class="col-sm-2"></div>
  </div>
  
  <div class="row container" style="height:488px;">
    <% @products.each do |product| %>
      <div class="col-sm-4">
	    <%= image_tag(product.image_url,height:'160',weight:'160', :class => "searchImagesContainer") if product.image_url.present? %>
	    <p><%= link_to truncate(product.productname,:length =>25,:omission => '.....'),product %></p>
	    <p><%= number_to_currency product.unitcost %></p>
	    <p>
	    <% if current_user && current_user.admin? %>
		  <div class="row">
	        <div class="col-sm-2">
              <%= link_to 'Edit', edit_product_path(product) %>
			</div>
	        <div class="col-sm-2">
              <%= link_to 'Destroy', product, :method => :delete, :data => { :confirm => 'Are you sure you want to delete this product?' } %>
			</div>
			<div class="col-sm-8"></div>
	      </div>
		<% end %>
		</p>
	  </div>
	<% end %>
  </div>
 
  <p>
  <div class="row">
    <div class="col-sm-2"></div>
    <div class="col-sm-8">
      <%= will_paginate  @products %>
    </div>
    <div class="col-sm-2"></div>
  </div>
  </p>
<% end %>  

app/views/products/edit.html.erb
<h1> Editing product </h1>

<%=render 'product' %>

app/views/products/index.html.erb
<%= form_tag products_path, :method => 'get', :id => "products_search" do %>

  <div class="row">
    <div class="col-sm-4">
	  <h3>Products (<%= @products.count %>)</h3>
	</div>
	<div class="col-sm-4"></div>
    <div class="col-sm-4">
      <%= select_tag "sort_value", options_for_select(Product::SORT_VALUES), {:class => 'form-control', :prompt => "Sort"}%>
	</div>
  </div>

  <%= render "products/productCategory", products: @products %>
<% end %>

<% if current_user && current_user.admin? %>
  <p> <%= link_to 'New Product', new_product_path, class: "btn btn-primary buttonColor" %> </p>
<% end %>

<script>
  $(function() {
    $("form select").on("change", function() {
      $(this).closest("form").submit();
    });
  });
</script>

app/views/products/new.html.erb
<h1> New product </h1>

<%= render 'product' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div class="row">
  <div class="col-sm-3"> <%= image_tag(@product.image_url, :class => "productImagesContainer") if @product.image_url.present? %> </div>
  <div class="col-sm-7">
    <p id="productTitle"> <%= @product.productname %></p>
    <p> <%= number_to_currency @product.unitcost %> </p>
    <p> <%= @product.category.categoryname %> </p>
    <p> <%= raw @product.reviews %> </p>
  </div>
  <div class="col-sm-2">
    <p>
	  <%= link_to "Add to cart", add_cart_path , method: :post, class: "btn btn-primary buttonColor" %>
	</p>
    <% if current_user && current_user.admin? %>
	<div class="row">
	  <div class="col-sm-2">
        <%= link_to 'Edit', edit_product_path(@product) %> 
	  </div>
	  <div class="col-sm-1"></div>
	  <div class="col-sm-2">
        <%= link_to 'Back', products_path %> 
	  </div>
	  <div class="col-sm-7"></div>
	</div>
    <% end %>
  </div>
</div>