config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'

  get 'users/new'  
  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  resources :messages
  get 'contact' => 'messages#new'
  get 'news' => 'static_pages#news'
  get 'signup' => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  delete 'destroy' => 'carts#destroy'
  resources :users
  resources :categories, param: :categoryid
  resources :products, param: :productid do
    get :autocomplete_product_productname, :on => :collection
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resource :cart, only: [ :show ] do
    post "add", path: "add/:productid"
	get :checkout
  end
  get 'orders/order_history' => 'orders#order_history'
  resources :orders, only: [:index, :show, :create, :update] do
    member do
	  get :new_payment
	  post :pay
    end
  end
  
  get '*path' => redirect('/')

end

app/views/layouts/_cart.html.erb
<% if @cart %>
    <% if @cart.is_empty? %>
      <%= link_to ('<i id="nav-cart-count" class="glyphicon glyphicon-shopping-cart"></i> Cart').html_safe, cart_path %>
	<% else %>
	  <%= link_to ('<i id="nav-cart-count" class="glyphicon glyphicon-shopping-cart">'+"#{@cart.product_count}"+'</i> Cart').html_safe, cart_path %>
    <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">

  <small>
  <%= link_to image_tag("logo.svg", alt: "Achats logo", height: '137', width: '178'),
            'https://shopping-site-new.herokuapp.com/' %>

    <a href="https://shopping-site-new.herokuapp.com/">Ecommerce Site</a>
    by <a href="https://in.linkedin.com/pub/suma-chaganti/1b/8b2/807">Suma Chaganti</a>
	
  </small>
  
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "News", news_path %></li>
	  <li><%= link_to "Help",   help_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse noRoundedMargins" id="headerID">
  <div class="container">
    <%= link_to "Achats", root_path, id: "logo" %>
	
	
	<ul class="nav navbar-nav">
      <li><%= link_to "Products", products_path %></li>
      <li class="dropdown">
        <%= link_to "#", data: { toggle: "dropdown" } do %>
          Categories
          <span class="caret"></span>
        <%- end %>
        <ul class="dropdown-menu">
          <% @categories.each do |category| %>
            <li><%= link_to category.categoryname, category %></li>
          <% end %>
        </ul>
      </li>
	  <li>	   

	  
	  <%= form_tag products_path, :method => 'get', :id => "products_search" do %>
          <br>
		  <div class="row">
		    <div class="col-sm-10">
			  <%= text_field_tag :search, params[:search], class: "form-control input-xs search-query",
			  placeholder: "Search Products", type: "search", data: {autocomplete: autocomplete_product_productname_products_path} %>   
			  
              
			  
			</div>
			<div class="col-sm-1">
              <%= button_tag(type: 'submit', class: "btn btn-default btn-search btn-primary btn-xs") do %>
                <i class="glyphicon glyphicon-search"></i> 
              <% end %>  
			</div>
          </div>
		<% end  %>
	  </li>
	</ul>
	
	
    <nav>
      <ul class="nav navbar-nav navbar-right">
	    
		<li> <%= link_to "Sign up now!", signup_path %></li>
        
		<% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", edit_user_path(current_user) %></li>
              <li><%= link_to "Order History", :action=>"order_history", :controller=>"orders" %></li>
			  <% if current_user && current_user.admin? %>
			    <li><%= link_to "Manage Orders", orders_path%></li>
				<li><%= link_to "Manage Users", users_path%></li>
				<li><%= link_to "Manage Categories", categories_path%></li>
			  <% end %>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign in", login_path, class: "navbar-link" %></li>
        <% end %>
		<li> <%= render "layouts/cart" %> </li>
	  </ul>	  
    </nav>
  </div>
</header> 

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app='Achats'>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<script src="https://js.braintreegateway.com/v2/braintree.js"></script>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
  
    <%= render 'layouts/header' %>
    <div class="container">
	  <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
	  <!--<%= debug(params) if Rails.env.development? %>-->
    </div>
  </body>
</html>